name: Git Config Sync
version: "0.0.2"
slug: git-config-sync
description: Synchronize home assistant config from a git repository
url: "https://github.com/wesleygrimes/ha-addons/tree/main/git-config-sync"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  repo_url: ""
  repo_branch: "main"
schema:
  repo_url: str
  repo_branch: str
#image: "ghcr.io/home-assistant/{arch}-addon-example"
